### ISSUE TITLE
TypeError: typescript_1.updateIdentifier is not a function

### ISSUE THREAD

**Issue by TechQuery** [slune-org/ts-transform-asset#2]
When I use `ts-transform-asset` with **TypeScript 4.0.2**, I got an error:

> (node:13716) UnhandledPromiseRejectionWarning: TypeError: typescript_1.updateIdentifier is not a function
>      at IdentifierSynthesizer.visit (my-project\node_modules\ts-transform-asset\dist\visitors\IdentifierSynthesizer.js:19:46)

We may need to support TypeScript 4.x.

**Comment by sveyret** [comment]
Reference: https://github.com/microsoft/TypeScript/pull/35282
